#!/usr/bin/env python3
"""Print default patient-cart SUJ frame poses for the Isaac Sim scenes.

Edit the constants below and run this file without arguments.  The output is a
YAML ``frames:`` mapping that can be pasted into a scene configuration.
"""

from __future__ import annotations

import math



# Patient-cart layout constants.  The world origin is the center of the
# notional surgical workspace sphere.
SPHERE_DIAMETER_M = 0.40
PSM1_POLAR_ANGLE_DEG = 30.0       # left PSM: 30 degrees from vertical camera axis
PSM2_POLAR_ANGLE_DEG = 30.0       # right PSM: 30 degrees from vertical camera axis
PSM3_POLAR_ANGLE_DEG = 60.0       # right PSM: 30 degrees above horizontal
ECM_POLAR_ANGLE_DEG = 0.0         # ECM directly above the sphere


def _normalize(values: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(sum(value * value for value in values))
    return tuple(value / length for value in values)


def _shortest_arc_xyzw(source: tuple[float, float, float], target: tuple[float, float, float]) -> tuple[float, float, float, float]:
    """Quaternion rotating source onto target, with zero roll where possible."""
    source = _normalize(source)
    target = _normalize(target)
    cross = (
        source[1] * target[2] - source[2] * target[1],
        source[2] * target[0] - source[0] * target[2],
        source[0] * target[1] - source[1] * target[0],
    )
    dot = sum(a * b for a, b in zip(source, target))
    if dot < -0.999999:
        # This layout never needs the antiparallel case, but keep the helper
        # deterministic if the constants are changed later.
        axis = (1.0, 0.0, 0.0) if abs(source[0]) < 0.9 else (0.0, 1.0, 0.0)
        cross = (source[1] * axis[2] - source[2] * axis[1],
                 source[2] * axis[0] - source[0] * axis[2],
                 source[0] * axis[1] - source[1] * axis[0])
        quaternion = (*_normalize(cross), 0.0)
    else:
        quaternion = (*cross, 1.0 + dot)
    length = math.sqrt(sum(value * value for value in quaternion))
    return tuple(value / length for value in quaternion)


def _frame(position: tuple[float, float, float]) -> tuple[tuple[float, float, float], tuple[float, float, float, float]]:
    direction_to_center = _normalize(tuple(-value for value in position))
    # The imported dVRK model has its zero-joint shaft along local -Z.
    orientation = _shortest_arc_xyzw((0.0, 0.0, -1.0), direction_to_center)
    return position, orientation


def _polar_position(side: float, angle_deg: float) -> tuple[float, float, float]:
    radius = SPHERE_DIAMETER_M / 2.0
    angle = math.radians(angle_deg)
    return (side * radius * math.sin(angle), 0.0, radius * math.cos(angle))


def _format(values: tuple[float, ...]) -> str:
    cleaned = (0.0 if abs(value) < 5e-10 else value for value in values)
    return "[" + ", ".join(f"{value:.9f}" for value in cleaned) + "]"


def main() -> None:
    frames = {
        "PSM1": _frame(_polar_position(-1.0, PSM1_POLAR_ANGLE_DEG)),
        "PSM2": _frame(_polar_position(1.0, PSM2_POLAR_ANGLE_DEG)),
        "PSM3": _frame(_polar_position(1.0, PSM3_POLAR_ANGLE_DEG)),
        "ECM": _frame(_polar_position(0.0, ECM_POLAR_ANGLE_DEG)),
    }
    print("# Generated by scripts/generate_cart_frames.py")
    print("# Positions are RCM/base poses in meters; orientations are ROS xyzw.")
    print("frames:")
    for name, (position, orientation) in frames.items():
        print(f"  {name}: {{position: {_format(position)}, orientation_xyzw: {_format(orientation)}}}")


if __name__ == "__main__":
    main()
